version: "3.8"

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE}
    container_name: bram-model
    env_file:
      - ".env"
    tty: true
    stdin_open: true
    volumes:
      - ./:/workspace
      - $HOME/.ssh:/root/.ssh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]