version: "3.8"

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bram-model
    env_file:
      - ".env"
    tty: true
    stdin_open: true
    volumes:
      - ./:/workspace
      - $HOME/.ssh:/root/.ssh